"""Add image_url to truck_reviews

Revision ID: 68cbe78c767e
Revises: 13dc05768077
Create Date: 2026-05-02 18:48:34.140742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68cbe78c767e'
down_revision = '13dc05768077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_reviews', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
